### ISSUE TITLE
Add Vector::AbsMax and AbsMin

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-math#102]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-math/issues/102)) by Martin Pecka (Bitbucket: [peci1](https://bitbucket.org/%7B41691c43-4ae0-49ba-ba45-3c36439f5af2%7D/)).**

----------------------------------------
# Summary

Basically, I’d like to add a function that would do the same as

```
math::Vector3d v = ...;
v.Abs().Max()
v.Abs().Min()
```

but without the unnecessary cost for creating new objects.

# Motivation

Sometimes one is not interested in positiveness/negativeness of the values in a vector, but just in their magnitude.

# Describe alternatives you've considered

One can use the Abs\(\).Max\(\) chain, but that leads to unncessary temporary object construction \(unless the compiler optimizes it very well\).

I’m not really sure about the name of the new methods, though. Alternatively, MaxMagnitude/MinMagnitude, MaxAbs/MinAbs…

# Additional context

‌

**Comment by chapulina** [comment]
The functions are there:

https://github.com/ignitionrobotics/ign-math/blob/b5306cc9ea8e7ac2075547b227eb5e6c738efb3e/include/ignition/math/Vector3.hh#L312-L328
