### ISSUE TITLE
Build Faiure with Ignition Math 6.4.0

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-math#104]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-math/issues/104)) by acxz (Bitbucket: [avcxz](https://bitbucket.org/%7B9dedb9bd-d101-4691-882b-c20ed6bbe205%7D/)).**

----------------------------------------
# Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:  
       * Checked the Q&A board for common solutions: http://answers.gazebosim.org  
    X  * Checked that your issue isn't already filed.  
   N/A * Checked that there is not already an Ignition package that provides the described functionality: https://ignitionrobotics.org/libs

# Description 

I am trying to install ignition-math 6.4.0, but the build fails for me. 

# Steps to Reproduce

1. mkdir build && cd build && cmake .. -DCMAKE\_BUILD\_TYPE=Release  
2. make

**Expected behavior:**  

The build should succeed.

**Actual behavior:**

Errors out. Build log: https://gist.github.com/acxz/b82cb035afa55339387361ba62353a9a

**Reproduces how often:** 

100%

# Versions

ArchLinux  
GCC: 9.2  
Ruby: 2.7.0

# Additional Information

Note: Downgrading to ruby 2.6.5 allows for the build to succeed.

‌

**Comment by acxz** [comment]
The error still occurs on Ruby: 2.7.1.

**Comment by acxz** [comment]
Note users have also reported that using the latest swig at head works: https://aur.archlinux.org/packages/ignition-math#comment-725387

**Comment by acxz** [comment]
Looks like ign-math 6.5.0 build works with the latest release swig. Closing this issue.

**Comment by chapulina** [comment]
Thanks for following up, closing!
