### ISSUE TITLE
Add AxisAlignedBox operator + for Vector3

### ISSUE THREAD

**Issue by chapulina** [ignitionrobotics/ign-math#121]
The `AxisAlignedBox` class has an `operator-` to translate the box by a vector, but oddly, there's no equivalent `operator+`:

https://github.com/ignitionrobotics/ign-math/blob/fdbd226d70885e85e265d7c61cfa9014bee1a33a/include/ignition/math/AxisAlignedBox.hh#L125-L128

This was desired on https://github.com/ignitionrobotics/ign-gazebo/pull/125/

**Comment by scpeters** [comment]
Closed by #122.
