### ISSUE TITLE
Document how to use Ruby interface

### ISSUE THREAD

**Issue by chapulina** [ignitionrobotics/ign-math#136]
See the discussion in https://github.com/ignitionrobotics/ign-math/issues/134#issuecomment-659048663.

We have Ruby bindings, but it's not easy to find out how to use them.

Things that need to be documented:

* Requirements (i.e. `ruby-dev` and `swig`)
* Usage
* How to test

**Comment by luccosta** [comment]
Planning to start on this issue today but I'm little lost on how to do it. Must I put the documentation in README using master branch?

**Comment by chapulina** [comment]
Thanks, @luccosta . The README sounds good to me.

I think you can mention the required dependencies under [source install prerequisites](https://github.com/ignitionrobotics/ign-math#prerequisites).

And I recommend targeting the `ign-math6` branch, and we'll merge it forward afterwards.

**Comment by luccosta** [comment]
Thanks for the guidance @chapulina . I dont know if the style used was the expected, but love to hear advices to improve documentation.
