### ISSUE TITLE
Could not find a package configuration file provided by "ignition-cmake2"

### ISSUE THREAD

**Issue by kjj3502** [ignitionrobotics/ign-math#238]
## Environment
* OS Version: Ubuntu 20.04.3 LTS
* Source or binary build?
 This build is via "https://github.com/ignition-release/ignition_math6_vendor"
* Log
Starting >>> ignition_math6_vendor
--- stderr: ignition_math6_vendor
Cloning into 'ignition-math6-6.8.0'...
HEAD is now at 6b5c704 🎈 6.8.0 (#202)
CMake Error at CMakeLists.txt:12 (find_package):
  By not providing "Findignition-cmake2.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "ignition-cmake2", but CMake did not find one.

  Could not find a package configuration file provided by "ignition-cmake2"
  (requested version 2.0.0) with any of the following names:

    ignition-cmake2Config.cmake
    ignition-cmake2-config.cmake

  Add the installation prefix of "ignition-cmake2" to CMAKE_PREFIX_PATH or
  set "ignition-cmake2_DIR" to a directory containing one of the above files.
  If "ignition-cmake2" provides a separate development package or SDK, be
  sure it has been installed.

make[2]: *** [ignition-math6-6.8.0-prefix/src/ignition-math6-6.8.0-stamp/ignition-math6-6.8.0-configure] Error 1
make[1]: *** [CMakeFiles/ignition-math6-6.8.0.dir/all] Error 2
make: *** [all] Error 2

**Comment by chapulina** [comment]
> This build is via "https://github.com/ignition-release/ignition_math6_vendor"

Can you list the steps that you took to build it?

**Comment by kjj3502** [comment]
Thanks for your help.

I took the full steps from the below link.
https://ros2-qnx-documentation.readthedocs.io/en/latest/build_from_source.html

From https://gitlab.com/qnx/ros2/ros2_qnx/-/blob/master/qnx_deps.repos, "https://github.com/ignition-release/ignition_math6_vendor" is called as follows.

![image](https://user-images.githubusercontent.com/40957174/133702645-6ad56f3b-fa28-47bf-aba9-7c65019cd0fb.png)

As you can see the log, this fails occurred at commit #202. So, I downloaded it and tried to build as follows
 1. git clone https://github.com/ignitionrobotics/ign-math.git
 2. git reset --hard 6b5c704a6b5bfc05d06b2f4b8a6b3b7adb6d8dc8
 3. cd ign-math/
 4. mkdir build
 5. cd build/
 6. cmake ..

The result shows that the fails is reproduced but after installing libignition-cmake2-dev, it's resoloved.
and I found something in build/CMakeCache.txt.
Before installing libignition-cmake2-dev, ignition-cmake2_DIR:PATH=ignition-cmake2_DIR-NOTFOUND
After  installing libignition-cmake2-dev, ignition-cmake2_DIR:PATH=/usr/share/cmake/ignition-cmake2

When I tried to build with my steps even after installing libignition-cmake2-dev, the fail occurred as well.
And I checked in build/aarch64le/ignition_math6_vendor/ignition-math6-6.8.0-prefix/src/ignition-math6-6.8.0-build/CMakeCache.txt. It shows ignition-cmake2_DIR:PATH=ignition-cmake2_DIR-NOTFOUND.

I'm not sure how I can apply setting ignition-cmake2_DIR:PATH during building

**Comment by chapulina** [comment]
Thanks for the extra context. I think those instructions are missing a rosdep install step, i.e.

```
sudo rosdep init
rosdep update
cd ~/ros2_rolling
rosdep install --from-paths src --ignore-src -r -y
```

This needs to be done after 

```
vcs import src < ros2.repos
```

**Comment by kjj3502** [comment]
After installing the steps you mentioned above, the fail occurred as well.
Could you advise how/when ignition-cmake2_DIR:PATH in build/CMakeCache.txt is set?

**Comment by chapulina** [comment]
> After installing the steps you mentioned above, the fail occurred as well.

Strange, that should have installed `libignition-cmake2-dev`, which you said fixes the issue. Did you see any errors? Did it install anything else?

> Could you advise how/when ignition-cmake2_DIR:PATH in build/CMakeCache.txt is set?

I'm not sure, but I think that this shouldn't be solved at the CMake level. I think there's something else wrong with your setup. You shouldn't be mixing the vendor packages with source builds of the libraries.

**Comment by kjj3502** [comment]
I really appreciate your help.

From https://raw.githubusercontent.com/ros2/ros2/master/ros2.repos, https://github.com/ignition-release/ignition_cmake2_vendor is called.

![image](https://user-images.githubusercontent.com/40957174/133712860-29ffd985-8e34-4f59-aeac-db27fcef1f2c.png)

ignition-math6 seems to refer to ignition-cmake2_DIR:PATH from "ignition_cmake2_vendor". As you see see the below, Path is also "NOTFOUD" in ignition-cmake2_vendor.

![image](https://user-images.githubusercontent.com/40957174/133712937-fd79b8c0-285b-4a45-9bb0-724f7fae850b.png)

It looks like it's related to my setup like you mentioned. 
It would be appreciated if you could advise something?

**Comment by kjj3502** [comment]
I found some workaround.

By adding "-Dignition-cmake2_DIR:PATH=/usr/share/cmake/ignition-cmake2" in ~/ros2_rolling_1/src/ignition/ignition_math6_vendor$ vi CMakeLists.txt, build is successfully done.

Thanks for your help.

**Comment by XQSwx** [comment]
I also encountered this problem. Although the above method can be used to compile, there is a problem. I changed the installation directory and this path is no longer applicable
