### ISSUE TITLE
Pose3_TEST.py fails in arm64 6.9.0~pre1

### ISSUE THREAD

**Issue by j-rivero** [ignitionrobotics/ign-math#250]
## Environment
* OS Version: Ubuntu Focal, arm64
* Source or binary build? during package creation

The [debbuilder job](https://build.osrfoundation.org/job/ign-math6-debbuilder/1084/console) from nightly today reports:
```
110/138 Test #110: Pose3_TEST.py ..........................***Failed    1.29 sec
......E
======================================================================
ERROR: test_stream_out (__main__.TestPose3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/ign-math6-debbuilder/build/ign-math/src/python/Pose3_TEST.py", line 145, in test_stream_out
    self.assertAlmostEqual(str(p), "0.1 1.2 2.3 0 0.1 1")
  File "/usr/lib/python3.8/unittest/case.py", line 943, in assertAlmostEqual
    diff = abs(first - second)
TypeError: unsupported operand type(s) for -: 'str' and 'str'

----------------------------------------------------------------------
Ran 7 tests in 0.028s

FAILED (errors=1)
```

Seems to happen when "subtracting a string from another that contains numbers in both strings" which seems to me the thing what we are doing here. Why is not failing in other arches?

## Description
* Expected behavior: test to pass
* Actual behavior: fails making the packaging job to fail

**Comment by scpeters** [comment]
I think the problem is that `assertAlmostEqual` is meant for numeric types, not string types. The method starts by comparing with `==` and returning quickly if they match exactly, which I believe is why it works in most cases:

https://github.com/python/cpython/blob/v3.8.12/Lib/unittest/case.py#L923-L939

my guess is that the pose strings don't match exactly on arm64, which is causing `assertAlmostEqual` to fail drastically

**Comment by scpeters** [comment]
I've opened https://github.com/ignitionrobotics/ign-math/pull/255 to use `assertEqual` instead of `assertAlmostEqual`, which should improve the error message, but I still expect the test to fail.

**Comment by scpeters** [comment]
trying an arm64 build of 6.9.1~pre1:

* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign-math6-debbuilder&build=1111)](https://build.osrfoundation.org/job/ign-math6-debbuilder/1111/) https://build.osrfoundation.org/job/ign-math6-debbuilder/1111/

**Comment by scpeters** [comment]
the test failure is more clear now:

~~~
110/138 Test #110: Pose3_TEST.py ..........................***Failed    0.10 sec
......F
======================================================================
FAIL: test_stream_out (__main__.TestPose3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jenkins/workspace/ign-math6-debbuilder/build/ignition-math-6.9.1~pre1/src/python/Pose3_TEST.py", line 145, in test_stream_out
    self.assertEqual(str(p), "0.1 1.2 2.3 0 0.1 1")
AssertionError: '0.1 1.2 2.3 -0 0.1 1' != '0.1 1.2 2.3 0 0.1 1'
- 0.1 1.2 2.3 -0 0.1 1
?             -
+ 0.1 1.2 2.3 0 0.1 1


----------------------------------------------------------------------
Ran 7 tests in 0.001s

FAILED (failures=1)
~~~

**Comment by scpeters** [comment]
potential fix in https://github.com/ignitionrobotics/ign-math/pull/257
