### ISSUE TITLE
Add setter/getter for Pose's each element

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-math#35]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-math/issues/35)) by Louise Poubel (Bitbucket: [chapulina](https://bitbucket.org/%7B5cfa2075-477b-4ded-bdb9-8d2479544ec4%7D/), GitHub: [chapulina](https://github.com/chapulina)).**

----------------------------------------
It would be helpful to be able to do `pose.X()` instead of `pose.Pos.X()`.

How about this?

* `pose.Pos.X()` -> `pose.X()`
* `pose.Pos.Y()` -> `pose.Y()`
* `pose.Pos.Z()` -> `pose.Z()`
* `pose.Rot.Roll()` -> `pose.Roll()`
* `pose.Rot.Pitch()` -> `pose.Pitch()`
* `pose.Rot.Yaw()` -> `pose.Yaw()`

**Comment by pxalcantara** [comment]
Currently I'm working on this issue!
