### ISSUE TITLE
Jammy CI now failing for ign-math6

### ISSUE THREAD

**Issue by scpeters** [ignitionrobotics/ign-math#383]
## Environment
* OS Version: Ubuntu 22.04
* Source or binary build? source build of ign-math6 as of d5155d2711531eb2f2aac40a1ee93b46fda9a592

## Description
* Expected behavior: CI runs correctly on Ubuntu 22.04 Jammy (it ran successfully in https://github.com/ignitionrobotics/ign-math/pull/378)
* Actual behavior: the build fails

## Steps to reproduce

1. Run a GitHub actions workflow on Ubuntu Jammy
2.
3.

## Output

~~~
CMake Error in src/python_pybind11/CMakeLists.txt:
    Imported target "pybind11::module" includes non-existent path
  
      "/usr/local/include/python3.10"
  
    in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
  
    * The path was deleted, renamed, or moved to another location.
  
    * An install or uninstall procedure did not complete successfully.
  
    * The installation package was faulty and references files it does not
    provide.
~~~

**Comment by ahcorde** [comment]
PR https://github.com/ignitionrobotics/ign-math/pull/384
