### ISSUE TITLE
Create reference frame class [gazebo issue 1486]

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-math#61]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-math/issues/61)) by Louise Poubel (Bitbucket: [chapulina](https://bitbucket.org/%7B5cfa2075-477b-4ded-bdb9-8d2479544ec4%7D/), GitHub: [chapulina](https://github.com/chapulina)).**

----------------------------------------
Moving Gazebo issue 1486 here now that gazebo::math has been fully deprecated. Please consider the discussion on that issue:

https://bitbucket.org/osrf/gazebo/issues/216/pose-addition-and-subtraction-needs-work

I believe work on this has started on branch [frame_graph](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-math/branch/frame_graph#diff). See [pull request #65](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-math/pull-requests/65) and [pull request #66](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-math/pull-requests/66).

**Comment by scpeters** [comment]
I believe this is now handled by frame semantics in libsdformat
