### ISSUE TITLE
error printing vectors with +-inf [gazebo issue 2020]

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-math#64]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-math/issues/64)) by Louise Poubel (Bitbucket: [chapulina](https://bitbucket.org/%7B5cfa2075-477b-4ded-bdb9-8d2479544ec4%7D/), GitHub: [chapulina](https://github.com/chapulina)).**

----------------------------------------
Moving Gazebo issue 2020 here now that gazebo::math has been fully deprecated. Please consider the discussion on that issue:

https://bitbucket.org/osrf/gazebo/issues/2020/error-printing-vectors-with-inf

The same problem occurs in ignition-math:

https://github.com/ignitionrobotics/ign-math/blob/2981c125c458d7dac097fc6e014901e72d691fac/include/ignition/math/Vector3.hh#L706

**Comment by chapulina** [comment]
New Gazebo issue location: https://osrf-migration.github.io/gazebo-gh-pages/#!/osrf/gazebo/issues/2020/page/1

**Comment by chapulina** [comment]
Closed by #168
