### ISSUE TITLE
Consider adding Color and Time classes

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-math#66]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-math/issues/66)) by Louise Poubel (Bitbucket: [chapulina](https://bitbucket.org/%7B5cfa2075-477b-4ded-bdb9-8d2479544ec4%7D/), GitHub: [chapulina](https://github.com/chapulina)).**

----------------------------------------
Consider moving [`gazebo::common::Color`](https://bitbucket.org/osrf/gazebo/src/56be256c4ba911e9ffb6fece23b0c51170f6dbdf/gazebo/common/Color.hh?fileviewer=file-view-default) / `ignition::common::Color` and [`gazebo::common::Time`](https://bitbucket.org/osrf/gazebo/src/56be256c4ba911e9ffb6fece23b0c51170f6dbdf/gazebo/common/Time.hh?fileviewer=file-view-default) / `ignition::common::Time` here. 

While it can be argued that these are not strictly "math" concepts, we could draw a parallel to existing ignition math classes such as [`Temperature`](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-math/pull-requests/113/temperature-class/diff). They're basically different ways of storing numbers which have special semantics.

On a less important note, this could also benefit ign-msgs, which already depends on ignition-math and could provide [conversions](https://github.com/ignitionrobotics/ign-msgs/blob/b6a4fb58696409fb6aac243e8affb3aaa110f71d/include/ignition/msgs/Utility.hh#L30) for the `time` and `color` messages.

**Comment by chapulina** [comment]
`ignition::math::Color` has been added and we're using `std::chrono` for time, see https://github.com/ignitionrobotics/ign-common/issues/61.
