### ISSUE TITLE
Fix test coverage on gz11 branch

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-math#94]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-math/issues/94)) by Steve Peters (Bitbucket: [Steven Peters](https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/), GitHub: [scpeters](https://github.com/scpeters)).**

----------------------------------------
test coverage is low becuase it is not properly excluding gtest and `*_TEST.cc` files

https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-math/pull-requests/268/fix-compilation-using-gcc8-and-add-support/diff#comment-66512565

**Comment by chapulina** [comment]
The `gz11` branch isn't used anymore, and the latest branches don't have the tests included in the coverage, so I think this issue can be closed.

https://codecov.io/gh/ignitionrobotics/ign-math/branch/ign-math6
